spring:
  application:
    name: medicare-health-systems

  datasource:
    url: jdbc:postgresql://localhost:5432/medicare_db
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

application:
  security:
    jwt:
      # Read from environment variable
      # Fallback value only for local development
      secret-key: ${JWT_SECRET:9YN1AS4nHG0BcmE/zplaX4q6zEymFQXez6X+VJEYIV4=}

      # 24 hours
      expiration: 86400000

      refresh-token:
        # 7 days
        expiration: 604800000

logging:
  level:
    org.springframework.security: DEBUG